[2022-04-15 13:52:43,065] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2020-01-21T00:00:00+00:00 [queued]>
[2022-04-15 13:52:43,929] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2020-01-21T00:00:00+00:00 [queued]>
[2022-04-15 13:52:43,930] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-15 13:52:43,998] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-15 13:52:43,998] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-15 13:52:44,967] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): task_2> on 2020-01-21 00:00:00+00:00
[2022-04-15 13:52:45,116] {standard_task_runner.py:52} INFO - Started process 117150 to run task
[2022-04-15 13:52:45,296] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', 'scheduled__2020-01-21T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp0u4jjoek', '--error-file', '/tmp/tmpkt916a7_']
[2022-04-15 13:52:45,653] {standard_task_runner.py:80} INFO - Job 110: Subtask task_2
[2022-04-15 13:52:50,290] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_2 scheduled__2020-01-21T00:00:00+00:00 [running]> on host 10.0.2.15
[2022-04-15 13:52:54,848] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=solfa
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-01-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-21T00:00:00+00:00
[2022-04-15 13:52:57,870] {python.py:175} INFO - Done. Returned value was: None
[2022-04-15 13:52:58,154] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200121T000000, start_date=20220415T135243, end_date=20220415T135258
[2022-04-15 13:52:58,844] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-15 13:53:01,483] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
