[2022-04-14 14:57:50,736] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2022-04-13T00:00:00+00:00 [queued]>
[2022-04-14 14:57:50,804] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2022-04-13T00:00:00+00:00 [queued]>
[2022-04-14 14:57:50,804] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-14 14:57:50,804] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-14 14:57:50,804] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-14 14:57:50,914] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): task_2> on 2022-04-13 00:00:00+00:00
[2022-04-14 14:57:50,917] {standard_task_runner.py:52} INFO - Started process 45566 to run task
[2022-04-14 14:57:50,936] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', 'scheduled__2022-04-13T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp60o9q6i5', '--error-file', '/tmp/tmpw60is_vu']
[2022-04-14 14:57:51,019] {standard_task_runner.py:80} INFO - Job 16: Subtask task_2
[2022-04-14 14:57:51,670] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_2 scheduled__2022-04-13T00:00:00+00:00 [running]> on host 10.0.2.15
[2022-04-14 14:57:51,955] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=solfa
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-04-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-13T00:00:00+00:00
[2022-04-14 14:57:54,960] {python.py:175} INFO - Done. Returned value was: None
[2022-04-14 14:57:54,989] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20220413T000000, start_date=20220414T145750, end_date=20220414T145754
[2022-04-14 14:57:55,050] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-14 14:57:55,125] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
