[2022-04-15 13:52:10,917] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2020-01-19T00:00:00+00:00 [queued]>
[2022-04-15 13:52:11,854] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2020-01-19T00:00:00+00:00 [queued]>
[2022-04-15 13:52:11,887] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-15 13:52:11,888] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-15 13:52:11,888] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-15 13:52:12,809] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): task_2> on 2020-01-19 00:00:00+00:00
[2022-04-15 13:52:12,927] {standard_task_runner.py:52} INFO - Started process 115903 to run task
[2022-04-15 13:52:13,053] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', 'scheduled__2020-01-19T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpeet0koxv', '--error-file', '/tmp/tmpg5kl3lq0']
[2022-04-15 13:52:13,322] {standard_task_runner.py:80} INFO - Job 102: Subtask task_2
[2022-04-15 13:52:18,915] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_2 scheduled__2020-01-19T00:00:00+00:00 [running]> on host 10.0.2.15
[2022-04-15 13:52:23,856] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=solfa
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-01-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-19T00:00:00+00:00
[2022-04-15 13:52:26,910] {python.py:175} INFO - Done. Returned value was: None
[2022-04-15 13:52:36,552] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200119T000000, start_date=20220415T135211, end_date=20220415T135236
[2022-04-15 13:52:37,561] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-15 13:52:39,533] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
