[2022-04-15 13:51:40,680] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2020-01-18T00:00:00+00:00 [queued]>
[2022-04-15 13:51:42,017] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2020-01-18T00:00:00+00:00 [queued]>
[2022-04-15 13:51:42,018] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-15 13:51:42,030] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-15 13:51:42,115] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-15 13:51:42,998] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): task_2> on 2020-01-18 00:00:00+00:00
[2022-04-15 13:51:43,245] {standard_task_runner.py:52} INFO - Started process 114664 to run task
[2022-04-15 13:51:43,660] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', 'scheduled__2020-01-18T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpcy8gl7cu', '--error-file', '/tmp/tmp7_h9rbob']
[2022-04-15 13:51:43,939] {standard_task_runner.py:80} INFO - Job 100: Subtask task_2
[2022-04-15 13:51:49,906] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_2 scheduled__2020-01-18T00:00:00+00:00 [running]> on host 10.0.2.15
[2022-04-15 13:51:54,824] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=solfa
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-01-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-18T00:00:00+00:00
[2022-04-15 13:51:57,987] {python.py:175} INFO - Done. Returned value was: None
[2022-04-15 13:51:59,268] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200118T000000, start_date=20220415T135140, end_date=20220415T135159
[2022-04-15 13:52:00,270] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-15 13:52:02,514] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
